"""empty message

Revision ID: 5b20230db28d
Revises: c12f19097c2e
Create Date: 2020-01-14 10:07:27.940915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b20230db28d'
down_revision = 'c12f19097c2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'image_link')
    op.add_column('Show', sa.Column('image_link', sa.String(length=500), nullable=True))
    op.add_column('Venue', sa.Column('genres', sa.String(length=30), nullable=True))
    op.drop_column('Venue', 'image_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'genres')
    op.drop_column('Show', 'image_link')
    op.add_column('Artist', sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
